  </div>

  <p id="Fusszeile">&copy; Heiner Jostkleigrewe - www.jverein.de - heiner@jverein.de</p>
</div>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-2013737-1";
urchinTracker();
</script>
    <!-- 
    $Log: footer.inc,v $
    Revision 1.1  2009/05/08 14:46:22  jost
    shtml - php

    Revision 1.5  2009/05/03 15:33:30  jost
    Neue Homepage

    -->

</body>
</html>

